### ISSUE TITLE
/のエスケープ問題

### ISSUE THREAD

**Issue by fumi** [tzhaya/jircas-json-ld#9]
JSON-LDでは、slashをbackslashでエスケープしないことになっています。

8.6 Data Round Tripping
https://json-ld.org/spec/latest/json-ld-api/#data-round-tripping

> Some JSON serializers, such as PHP's native implementation in some versions, backslash-escape the forward slash character. For example, the value http://example.com/ would be serialized as http:\/\/example.com\/. This is problematic as other JSON parsers might not understand those escaping characters. There is no need to backslash-escape forward slashes in JSON-LD. To aid interoperability between JSON-LD processors, forward slashes MUST NOT be backslash-escaped.

**Comment by tzhaya** [comment]
ご指摘ありがとうございました。さきほど、slashのbackslashによるエスケープをなしとしました。
